services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://eshalumrahessentials:eshal%400102@cluster0.woukx9j.mongodb.net/hajjUmrah?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  mongodb_data: 