spring:
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI}
      auto-index-creation: true
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:changeme}

server:
  port: ${PORT:8080}
  servlet:
    context-path: / 